included:
  - Sources
  - Tests

excluded:
  - .build
  - PulpDemoApp

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - discouraged_optional_boolean
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - vertical_whitespace_closing_braces

analyzer_rules:
  - unused_declaration

disabled_rules:
  - trailing_comma
  - todo

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 700

function_body_length:
  warning: 60
  error: 120

nesting:
  type_level: 2

identifier_name:
  min_length: 1
  excluded:
    - id
    - x
    - y
    - w
    - p
